url: "https://www.jackforgash.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "JF" # the name of your site, e.g. ACME Corp.

collections:
  backyard:
    output: true
  library:
    output: true
  office:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
