title: forgash_
description: Personal website for Jack Forgash - Blockchain Data Professional
baseurl: ""
url: "https://forgash.io"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CLAUDE.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

sass:
  style: compressed